title: One on One With Matt
email: matt@notch8.com
description: >- # this means to ignore newlines until "baseurl:"
  Tips and help with the tools we use as developers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  winescout

# Build settings
# theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.16.6"
plugins:
  - jekyll-feed
  - jekyll-include-cache


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
